### ISSUE TITLE
errnoException

### ISSUE THREAD

**Issue by mulhoon** [PatrickWolleb/SoundFontJS#2]
Hi, this looks very useful.

Unfortunately I get this error.. Do you know what it might be?
Thanks

```
child_process.js:927
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:980:11)
    at ChildProcess.spawn (child_process.js:927:11)
    at exports.spawn (child_process.js:715:9)
    at Object.exports.execFile (child_process.js:607:15)
    at exports.exec (child_process.js:578:18)
    at cut (/Users/Mulhoon/.nvm/v0.10.18/lib/node_modules/sfjs/bin/sfjs:93:5)
    at /Users/Mulhoon/.nvm/v0.10.18/lib/node_modules/sfjs/bin/sfjs:185:11
    at /Users/Mulhoon/.nvm/v0.10.18/lib/node_modules/sfjs/bin/sfjs:80:14
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
```

**Comment by mulhoon** [comment]
Ok, this issue was because of the file limit. `ulimit -n 10000` did not help as it has changed now. 

this worked for me `sudo launchctl limit maxfiles 1000 10000`

Also here is a good guide to installing the dependencies. Might be worth including in your readme.
http://www.emersonlackey.com/article/command-line-ogg-conversion

Thanks for the script, now works perfectly.

**Comment by PatrickWolleb** [comment]
Nice one. Glad to hear!
