### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by 798714773** [PatrickWolleb/SoundFontJS#4]
```
Error: ENOENT: no such file or directory, open '/Users/c/Desktop/soundfont/acoustic_grand_piano/A0.ogg'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at oggToJS (/usr/local/lib/node_modules/sfjs/bin/sfjs:140:19)
    at /usr/local/lib/node_modules/sfjs/bin/sfjs:215:17
    at /usr/local/lib/node_modules/sfjs/bin/sfjs:112:16
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:321:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/c/Desktop/soundfont/acoustic_grand_piano/A0.ogg'
}
```

**Comment by chadian** [comment]
I added logging to the code and this error was actually the result of previous files not being generated. The actual error I ran into was: `Bad CPU type in executable` which was coming from the packaged `sox` binary that wasn't suitable for macos. I did a `brew install sox` and changed this line in [bin/sfjs](https://github.com/PatrickWolleb/SoundFontJS/blob/master/bin/sfjs#L93):
```
exec(__dirname + '/../libs/sox ' + input + ' ' + BUILD_DIR + '/' +notesArray[i] + '.wav trim ' + s + ' ' + 2, function(err, stdout, stderr) {
```
to:
```
exec('sox ' + input + ' ' + BUILD_DIR + '/' +notesArray[i] + '.wav trim ' + s + ' ' + 2, function(err, stdout, stderr) {
```
so that it executes the globally brew-installed `sox` (that will work for macos).

After that I was able to get working builds.

As one possible permanent fix, `sox` should become an external dependency like `oggenc` and `lame`.
